tasks:
  task00: # unittest
    easy:
      train: "../tests/task/train_mock*"
      test:  "../tests/task/test_mock*"
    eval_test:
      train: "../tests/task/eval_test/eval*"
      test:  "../tests/task/eval_test/eval*"
  task00-multiagent: # unittest
    easy:
      train: "../tests/task/train_multiagent_mock*"
      test:  "../tests/task/test_multiagent_mock*"
    eval_test:
      train: "../tests/task/eval_test_multiagent/eval*"
      test:  "../tests/task/eval_test_multiagent/eval*"
  task0:
    no-traffic:
      train: "scenarios/task1/train_no-traffic*"
      test:  "scenarios/task1/train_no-traffic*"
    easy:
      train: "scenarios/task1/train_easy*"
      test:  "scenarios/task1/train_easy*"
    medium:
      train: "scenarios/task1/train_medium*"
      test:  "scenarios/task1/train_medium*"
    hard:
      train: "scenarios/task1/train_hard*"
      test:  "scenarios/task1/train_hard*"
  task1:
    no-traffic:
      train: "scenarios/task1/train_no-traffic*"
      test:  "scenarios/task1/test_no-traffic*"
    easy:
      train: "scenarios/task1/train_easy*"
      test:  "scenarios/task1/test_easy*"
    medium:
      train: "scenarios/task1/train_medium*"
      test:  "scenarios/task1/test_medium*"
    hard:
      train: "scenarios/task1/train_hard*"
      test:  "scenarios/task1/test_hard*"
  task2:
    lo-hi:
      train: "scenarios/task2/train_lo-hi*"
      test:  "scenarios/task2/test_lo-hi*"
    hi-lo:
      train: "scenarios/task2/train_hi-lo*"
      test:  "scenarios/task2/test_hi-lo*"
  task0-4agents:  # The name of the task.
    no-traffic:  # The level name.
      train: "scenarios/task0-4agents/train_no-traffic*"  # The relative path to the training scenarios.
      test: "scenarios/task0-4agents/test_no-traffic*"  # The relative path to the testing scenarios.
  task0-3agents:  # The name of the task.
    no-traffic:  # The level name.
      train: "scenarios/task0-4agents/train_no-traffic*"  # The relative path to the training scenarios.
      test:  "scenarios/task0-4agents/test_no-traffic*"  # The relative path to the testing scenarios.
  task0-2agents:  # The name of the task.
    no-traffic:  # The level name.
      train: "scenarios/task0-4agents/train_no-traffic*"  # The relative path to the training scenarios.
      test:  "scenarios/task0-4agents/test_no-traffic*"  # The relative path to the testing scenarios.
  task0-1agents:  # The name of the task.
    no-traffic:  # The level name.
      train: "scenarios/task0-4agents/train_no-traffic*"  # The relative path to the training scenarios.
      test:  "scenarios/task0-4agents/test_no-traffic*"  # The relative path to the testing scenarios.
