action_size: 1
agent_type: image
discrete_action_choices: 4
batch_size: 2048  # size of batch
lr: 3e-5
mini_batch_size: 64  # 64
epoch_count: 20
gamma: 0.99  # discounting
l: 0.95  # lambda used in lambda-return
eps: 0.2  # epsilon value used in PPO clipping
critic_tau: 1.0
actor_tau: 1.0
entropy_tau: 0.0
hidden_units: 512
seed: 2
logging_freq: 2
n_in_channels: 3
image_height: 256
image_width: 256
compression: zlib
